### ISSUE TITLE
Change all <img> to Gatsby Images for Better Performance

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/fairfield-programming.github.io#29]
This one is also pretty self-explanatory, just change over all of the images to Gatsby images so that they are much more performant when loading from the edge. 

Don't take this if it isn't your first issue. :)

**Comment by Andreas-Bombaert** [comment]
Hello, I would like to work on this issue as my first issue :)

**Comment by William-McGonagle** [comment]
@Andreas-Bombaert 
Sounds great- I'll assign it to you!

**Comment by Andreas-Bombaert** [comment]
[Here](https://github.com/fairfield-programming/fairfield-programming.github.io/pull/34) is the pull request for this issue, I explained a few issues I had with the use of this GatsbyImage plugin, and to be honest I don't know if this plugin is adapted for this use

**Comment by William-McGonagle** [comment]
Hey @Andreas-Bombaert

I will check out the pull as soon as possible- you said that there was a problem you had with Gatsby Image- what was the issue? 

Thanks-
Will

**Comment by Andreas-Bombaert** [comment]
Hello William,

it seems that the Gatsby Image plugin is not made to use json files to get the path of an image, you have to query the image data through a graphql query, which cannot work for remote images (Actually it could but it would need more queries if I'm correct). At first I thought that I would only have to replace <img> tags but it was not that simple :'(

Another way to use Gatsby images is to hardcode the path string in the GatsbyImage tag but your project is using json files to stock it, so I didn't want to interfer with your way to do and I used the graphql method, which does not work for dynamic components like `person.js`

There is also another issue of an image not loading correctly at first load on index page, this issue seems to be linked to deprecated or not up-to-date packages.

The last issue I had is that `gatsby-plugin-image` does not handle svg images, so we need to either convert logo.svg to png, or use another gatsby package to convert svg to component

All these issues put together, I'm asking myself if <img> tags would not be better for the project ahah

I hope that my english is readable,
Andréas

**Comment by William-McGonagle** [comment]
Hey @Andreas-Bombaert 

Yikes- that seems like a difficult problem. The SVG isn't as much a problem because Gatsby already optimizes them, but I will check out the dynamic images. Maybe there is some other library that will let us do dynamic-loaded images, but it is kind of stupid Gatsby Image doesn't do it by default.

Cheers,
Will

P.S. Your English is great

**Comment by William-McGonagle** [comment]
Hey @Andreas-Bombaert 

I checked out the code, and I understand the problem. I think you're right that Gatsby Image just wasn't built for a dynamic website like this. I merged in your code because you still put in the work, so you deserve to have the contributor status, but to get it into production I had to remove a lot of the Gatsby Image logic that you had added. 

It was awesome work that you did– great engineering, so I'm sorry that it can't be used in production. You should keep an eye on the project– if you're interested, the FPA could use a hand running some of our open-source websites (this is the first of three that we are launching in around a month), so just let me know. 

Thank you,
Will

**Comment by Andreas-Bombaert** [comment]
Thank you!

I have exams coming up in january but after that why not!
I'll let you know :)

Have a nice one,

Andréas

**Comment by William-McGonagle** [comment]
Sounds great @Andreas-Bombaert. Good luck with exams too!
